### PR TITLE
fix(jest): Use greatest known `jsc.target` instead of least

### LINKED ISSUE #98: Code coverage for safe navigation (?.)  is different between node 20 and 22 when using @swc/jest
When upgrading packages from node 20 to 22 some failed their jest coverage threshold. 
It happens in packages that use @swc/jest, in tests that use the save navigation operator, but don't test with null and non-null.

```javascript
// lib.js
export function thing(obj) {
  return obj?.key
}
```
```javascript
// test.js
//import { it } from 'node:test'
import { thing } from './lib.js'

it("tests thing", () => {
  thing({key: 1})
})
```

```javascript
jest.config.mjs
export default {
  collectCoverage: true,
  transform: {
    '^.+\\.js$': ['@swc/jest'],
  },
}
```
```json5
// package.json
{"type":"module","dependencies":{"@swc/jest":"^0.2.38","jest":"^29.7.0"}}
```

```console
$ mise exec node@22 --  npx jest
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------|---------|----------|---------|---------|-------------------
All files |     100 |       50 |     100 |     100 |
 lib.js   |     100 |       50 |     100 |     100 | 2
----------|---------|----------|---------|---------|-------------------

$ mise exec node@20 --  npx jest
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------|---------|----------|---------|---------|-------------------
All files |     100 |      100 |     100 |     100 |
 lib.js   |     100 |      100 |     100 |     100 |
----------|---------|----------|---------|---------|-------------------
```

I'm not sure if this should be considered a bug, in a sense it caught an uncovered branch.
However, this will make it harder to upgrade to node 22

* node:test's --experimental-test-coverage was consistent between 20 and 22, but shows 100% branch coverage when only testing the non-null case, and 66% when only testing null.
* vitest was consistent and showed 100% coverage with both node versions
* jest without swc was consistent and showed 100% coverage with both node versions

### PR DESCRIPTION
**Pull request by everett1992**
I noticed that code coverage was different between node 20 and 22 when using @swc/jest and tracked it back to swc falling back to es2018 for unknown node versions.

This change makes @swc/jest use the target of any lower node version

Fixes #98

### CODE REVIEW

File: packages/jest/index.ts [hunk 1]
```diff
@@ -4,7 +4,8 @@ import * as path from "path";
 import * as process from "process";
 import getCacheKeyFunction from "@jest/create-cache-key-function";
 import type { Transformer, TransformOptions } from "@jest/transform";
-import { parse as parseJsonC, type ParseError } from "jsonc-parser";
+import { parse as parseJsonC } from "jsonc-parser";
+import type { ParseError } from "jsonc-parser";
```
Comment (everett1992) [inline packages/jest/index.ts:8]: Prettier was failing with a SyntaxError, I guess the version doesn't understand inline type imports.

**Review by kdy1 — APPROVED** [review]
